version: '3'
services:
 brenovit-mysql:
  container_name: brenovit-mysql
  image: mysql/mysql-server:5.7
  environment:
   MYSQL_DATABASE: store
   MYSQL_ROOT_PASSWORD: brenovit
   MYSQL_ROOT_HOST: '%'
   MYSQL_USER: root
  ports:
   - "3306:3306"
  restart: always
 brenovit-application:
  build: .
  volumes: 
  - .:/app
  - ~/m2:/root/.m2
  working_dir: /app
  ports:
  - 8181:8181
  command: mvn clean spring-boot:run
  depends_on:
  - brenovit-mysql